FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app


COPY requirements.txt .


RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libpq-dev \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*


COPY entrypoint-backend.sh /usr/local/bin/entrypoint-backend.sh
RUN chmod +x /usr/local/bin/entrypoint-backend.sh


EXPOSE 8000

ENTRYPOINT ["/usr/local/bin/entrypoint-backend.sh"]