# Generated by Django 6.0.4 on 2026-05-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_padre'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='idx_items_usuario',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='idx_items_padre',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='idx_items_usuario_padre',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='idx_items_eliminado',
        ),
    ]
