# Generated by Django 6.0.4 on 2026-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_idx_items_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ruta',
        ),
        migrations.AddField(
            model_name='item',
            name='storage_key',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
