# Generated by Django 6.0.4 on 2026-05-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='storage_key',
        ),
    ]
