# Generated by Django 6.0.4 on 2026-05-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_file_item_idx_items_navegacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_nombre_en_carpeta',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_nombre_en_raiz',
        ),
    ]
