# Generated by Django 6.0.4 on 2026-05-31 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_eliminar_unique_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('file', models.CharField(max_length=500)),
                ('tamano_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='items.item')),
            ],
            options={
                'ordering': ['-numero'],
                'indexes': [models.Index(fields=['item', 'numero'], name='idx_version_item_numero')],
                'constraints': [models.UniqueConstraint(fields=('item', 'numero'), name='unique_item_version')],
            },
        ),
    ]
