# Generated by Django 6.0.4 on 2026-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('archivo', 'ARCHIVO'), ('carpeta', 'CARPETA')], max_length=10),
        ),
    ]
