# Generated by Django 6.0.4 on 2026-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('archivo', 'Archivo'), ('carpeta', 'Carpeta')], max_length=10),
        ),
    ]
