# Generated by Django 6.0.4 on 2026-05-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_ruta_item_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
