# Generated by Django 6.0.4 on 2026-05-19 17:27

import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_item_storage_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=items.models.upload_item_path),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['usuario', 'padre', 'eliminado'], name='idx_items_navegacion'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['usuario', 'eliminado'], name='idx_items_papelera'),
        ),
    ]
