# Generated by Django 6.0.4 on 2026-05-06 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('archivo', 'Archivo'), ('carpeta', 'Carpeta')], max_length=10)),
                ('ruta', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('favorito', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminado', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='users.archivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario'], name='idx_archivos_usuario'), models.Index(fields=['padre'], name='idx_archivo_padre'), models.Index(fields=['usuario', 'padre'], name='idx_archivo_usuario_padre'), models.Index(fields=['usuario', 'eliminado'], name='idx_usuario_eliminado')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('padre__isnull', False)), fields=('usuario', 'padre', 'nombre', 'eliminado'), name='unique_nombre_en_carpeta'), models.UniqueConstraint(condition=models.Q(('padre__isnull', True)), fields=('usuario', 'nombre', 'eliminado'), name='unique_nombre_en_raiz')],
            },
        ),
    ]
