# Imagen base de Node
FROM node:22-slim

# Instalamos Herramientas para desarrollo
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# El entrypoint instala dependencias y arrancamos Vue en modo dev
COPY entrypoint-frontend.sh /usr/local/bin/entrypoint-frontend.sh
RUN chmod +x /usr/local/bin/entrypoint-frontend.sh

EXPOSE 5173

ENTRYPOINT ["/usr/local/bin/entrypoint-frontend.sh"]
